print("Welcome to text adventure.")
choice1 = input("Please enter your name:")
print("Hello, " + choice1 + "!")
print("Let's start.")
print("You are in a strange world.")
print("Monsters are everywhere.")
print("You must protect a nearby town from an incoming massive attack.")
choice2 = input("So, will you REST, or PREPARE?")
if choice2 == "REST":
    print("You get some rest.")
    print("You wake up refreshed.")
    print("But as you look up to the town's gates, you see a man ringing a gong.")
    print()
    print()
    print()
    print()
    print()
    print("The monsters have arrived.")
    choice3 = input("Will you FIGHT? Or maybe HIDE.")
    if choice3 == "FIGHT":
        print("You run to the village gates, but you are tired from")
if choice2 == "PREPARE":
    print("You train in the the town's battle center.")
    print("After 3 hours, you take a quick break.")
    print("You feel like you could face anything after this training session.")
    print("You hear a gong being rung. It is the monster warning bell.")
    choice4 = input("Will you use a SWORD or a BOW and arrow?")